import type { Metadata } from "next";
import "@config/styles/globals.css";
import localFont from "next/font/local";

const uniqueFont = localFont({
  src: [
    {
      path: "../../../config/fonts/Unique-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../../config/fonts/Unique-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-unique",
  display: "swap",
});

const bicycletteFont = localFont({
  src: [
    {
      style: "normal",
      path: "../../../config/fonts/Bicyclette-Bold.woff",
      weight: "700",
    },
    {
      style: "normal",
      path: "../../../config/fonts/Bicyclette-Black.woff",
      weight: "800",
    },
  ],
  variable: "--font-bicyclette",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${uniqueFont.variable} ${bicycletteFont.variable} font-bicyclette antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
